### ISSUE TITLE
Sending a message doesn't work

### ISSUE THREAD

**Issue by yoniker** [cmpunches/Pofapi#1]
So sending a message doesn't work anymore.

I'm not too sure why. I can see that POF did add some priority to the post message, but adding that as well didn't help...It will be awesome if you can help me out here :)

**Comment by cmpunches** [comment]
Hey Yoniker.  Yes it looks like they made some changes to how sessions are being handled.  I'm doing a full rewrite for a 2.0 release.  Should be done soon.  The session check will be a bit hacky but is more functional.

**Comment by cmpunches** [comment]
Full rewrite is complete.  You should notice a great deal more stability and some new features as well.  Don't abuse it :)

**Comment by yoniker** [comment]
never ;)
