### ISSUE TITLE
Only works for united states zip codes

### ISSUE THREAD

**Issue by coinbroker1** [cmpunches/Pofapi#3]
Tried inputting alpha numeric values for Canadian postal codes via the editor and I keep getting an error 0 users found

**Comment by cmpunches** [comment]
Hey.  Thanks for reporting this.

Can you please show your code and the output?

**Comment by coinbroker1** [comment]
[session]
username = username	
password = pw
[search]
gender = m
target_gender = f
min_age = 18
max_age = 40
max_distance = 25
zipcode = L7N2Z8
# These can be left blank.
# I will need to create a map as these translate directly into
# uri parameters on the search.
interests =
min_height =
max_height =
marital_status =
relationshipage_id =
wants_children =
has_children =
drinks =
smokes =
does_drugs =
body_type =
smarts=
eye_color =
income =
profession =
hair_color =
religion =
country =
has_pets =
![pofapifail](https://user-images.githubusercontent.com/32800648/35064972-ba72c32c-fb99-11e7-8e5d-d377151592b6.png)

**Comment by cmpunches** [comment]
This is your config, and is needed, but can you show your code.  Also what python version are you using?

**Comment by coinbroker1** [comment]
3.6

**Comment by cmpunches** [comment]
Not a bug.  It's your max_distance setting.  You're not actually finding users.

And you want to pay attention to the only_online argument to POFSession.searchUsers method.

Sorry!

**Comment by cmpunches** [comment]
Also please use proper code formatting for config and code snippets so it's not treated as markdown.
Example:
```
[session]
username = ********
password = *********
[search]
gender = m
target_gender = f
min_age = 18
max_age = 40
max_distance = 25
zipcode = L7N2Z8
# These can be left blank.
# I will need to create a map as these translate directly into
# uri parameters on the search.
interests =
min_height =
max_height =
marital_status =
relationshipage_id =
wants_children =
has_children =
drinks =
smokes =
does_drugs =
body_type =
smarts=
eye_color =
income =
profession =
hair_color =
religion =
country =
has_pets =

```

**Comment by coinbroker1** [comment]
I upped my max distance to 999 and still getting the same issue. I can confirm there are users online within this zipcode using pof manually. When using a United States zipcode I have 0 issues.

**Comment by cmpunches** [comment]
With the following config on a retest:

```
[session]
username = *****
password = *****

[search]
gender = m
target_gender = f
min_age = 18
max_age = 40
max_distance = 250
zipcode = L7N2Z8
# These can be left blank.
# I will need to create a map as these translate directly into
# uri parameters on the search.
interests =
min_height =
max_height =
marital_status =
relationshipage_id =
wants_children =
has_children =
drinks =
smokes =
does_drugs =
body_type =
smarts=
eye_color =
income =
profession =
hair_color =
religion =
country =
has_pets =

```
The result was:

```
[ phanes@anvil.silogroup.lan ] << ~/pofapi-test/Pofapi >>

[- ./BroadcastExample.py 
Successfully logged in as user 'cpunchesful'.
Retrieved Page 1 (20 users)
Total Users Found: 5
Successfully sent message to user 158866339
Successfully sent message to user 169568011
Successfully sent message to user 81813591
Successfully sent message to user 166536652
Successfully sent message to user 169523024

```

This is not a bug.  You are not testing properly.  Character casing is not relevant.  The issue is that when you ran it users were not on and were when you tested in browser.  I am sorry that there are not more people in your area.  I am closing the ticket to prevent any more time being spent on it.
